# Debe coincidir con el nombre de los archivos en config-repo (loan-service*.properties)
spring.application.name=loan-service

# Perfil activo: define qué archivo de config-repo se aplica (dev -> loan-service-dev.properties)
spring.profiles.active=dev

# Dónde pedir la configuración al arrancar. "optional:" evita que falle si el servidor no está
spring.config.import=optional:configserver:http://localhost:8888
