spring.application.name=config-server

# Puerto estándar de Spring Cloud Config
server.port=8888

# Perfil "native": lee las configuraciones desde archivos locales (no desde Git)
spring.profiles.active=native

# Carpeta con los .properties. La ruta es relativa a config-server/ (donde se ejecuta mvn spring-boot:run)
spring.cloud.config.server.native.search-locations=file:../config-repo
